server:
  port: 8999
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/plain_admin?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
  #    druid:
  #      filters: stat
  resources:
    # 静态资源地址，多个以逗号分割
    # static-locations: classpath:static/,file:static/
    static-locations: classpath:static/,file:static/,classpath:template/


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 使用 mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.xiaosm.plainadmin.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl



logging:
  #  config: classpath:log4j.properties
  level:
    cn.xiaosm.plainadmin.mapper: debug
