server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yadmin?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    druid:
      filters: stat,wall
  resources:
    # 静态资源地址，多个以逗号分割
    # static-locations: classpath:static/,file:static/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 使用 mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.xiaosm.yadmin.**.entity
  # 支持统配符 * 或者 ; 分割
  type-enums-package: cn.xiaosm.yadmin.**.entity.enums
  configuration:
    # 下划线转驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 枚举类型处理器
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler

logging:
  #  config: classpath:log4j.properties
  level:
    cn.xiaosm.yadmin.mapper: debug
